CREATE SEQUENCE VAGAS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_VAGAS (
    ID INTEGER DEFAULT VAGAS_SEQ.NEXTVAL NOT NULL,
    TITULO VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    EMPRESA VARCHAR(20) NOT NULL
);
INSERT INTO TBL_VAGAS (TITULO, DESCRICAO, EMPRESA)
VALUES ('Desenvolvedor Java', 'Desenvolvimento de sistemas utilizando Java, Spring Boot, e outras tecnologias', 'TechCorp');
